$(document).ready(function(){
    $("#abrir").click(function(){
        $(".hospital1").fadeIn();
    });
    $("#cerrar").click(function(){
        $(".hospital1").fadeOut();
    });
    $("#abrir1").click(function(){
        $(".hospital2").fadeIn();
    });
    $("#cerrar1").click(function(){
        $(".hospital2").fadeOut();
    });
    $("#abrir2").click(function(){
        $(".hospital3").fadeIn();
    });
    $("#cerrar2").click(function(){
        $(".hospital3").fadeOut();
    });
});